spring:
  application:
    name: usage-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5435}/apiguard
    username: apiguard
    password: secret
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: apiguard
    password: secret
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: false
    table: usage_flyway_history
    locations: classpath:db/migration

server:
  port: 8082
